var searchData=
[
  ['saveusercommand_0',['SaveUserCommand',['../class_starter_app_1_1_view_models_1_1_user_detail_view_model.html#af1bf81286c8212571862a4f1aa6752f5',1,'StarterApp::ViewModels::UserDetailViewModel']]],
  ['searchtext_1',['SearchText',['../class_starter_app_1_1_view_models_1_1_user_list_view_model.html#a0c4f29b7d9b8c48b34cb07e1b65f01bc',1,'StarterApp::ViewModels::UserListViewModel']]],
  ['selectedrolefilter_2',['SelectedRoleFilter',['../class_starter_app_1_1_view_models_1_1_user_list_view_model.html#a0a5c9e9c3f5ac90d60f397474e11fe8a',1,'StarterApp::ViewModels::UserListViewModel']]],
  ['seterror_3',['SetError',['../class_starter_app_1_1_view_models_1_1_base_view_model.html#a1ed268c8a134fab27d92f6b68d0c4a55',1,'StarterApp::ViewModels::BaseViewModel']]],
  ['setup_20data_4',['Setup data',['../C:/Users/chris/ENU OneDrive/OneDrive - Edinburgh Napier University/Year 3/resit/SWE_resit2/setup/README.md#autotoc_md3',1,'']]],
  ['showmoreinfocommand_5',['ShowMoreInfoCommand',['../class_starter_app_1_1_view_models_1_1_about_view_model.html#a8a8b9574c99a4e4a8434e11b29a5a148',1,'StarterApp::ViewModels::AboutViewModel']]],
  ['showpasswordfields_6',['ShowPasswordFields',['../class_starter_app_1_1_view_models_1_1_user_detail_view_model.html#a8375b50593eedd18f0411bf85be89b12',1,'StarterApp::ViewModels::UserDetailViewModel']]],
  ['speaker_7',['Speaker',['../class_starter_app_1_1_database_1_1_models_1_1_conference.html#a459b20eb77fcf8d6d15e229343d0c9f2',1,'StarterApp::Database::Models::Conference']]],
  ['started_8',['Getting started',['../md__r_e_a_d_m_e.html#autotoc_md2',1,'']]],
  ['starterapp_9',['StarterApp',['../namespace_starter_app.html',1,'']]],
  ['starterapp_20app_10',['StarterApp app',['../md__r_e_a_d_m_e.html',1,'']]],
  ['starterapp_2eassemblyinfo_2ecs_11',['StarterApp.AssemblyInfo.cs',['../net8_80-maccatalyst_2maccatalyst-x64_2_starter_app_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../net8_80-windows10_80_819041_80_2win10-x64_2_starter_app_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['starterapp_2edatabase_2eassemblyinfo_2ecs_12',['StarterApp.Database.AssemblyInfo.cs',['../_starter_app_8_database_8_assembly_info_8cs.html',1,'']]],
  ['starterapp_2edatabase_2eglobalusings_2eg_2ecs_13',['StarterApp.Database.GlobalUsings.g.cs',['../_starter_app_8_database_8_global_usings_8g_8cs.html',1,'']]],
  ['starterapp_2eglobalusings_2eg_2ecs_14',['StarterApp.GlobalUsings.g.cs',['../net8_80-android_2_starter_app_8_global_usings_8g_8cs.html',1,'(Global Namespace)'],['../net8_80-maccatalyst_2maccatalyst-x64_2_starter_app_8_global_usings_8g_8cs.html',1,'(Global Namespace)'],['../net8_80-windows10_80_819041_80_2win10-x64_2_starter_app_8_global_usings_8g_8cs.html',1,'(Global Namespace)'],['../net9_80-maccatalyst_2maccatalyst-x64_2_starter_app_8_global_usings_8g_8cs.html',1,'(Global Namespace)'],['../net9_80-windows10_80_819041_80_2_starter_app_8_global_usings_8g_8cs.html',1,'(Global Namespace)']]],
  ['starterapp_2emigrations_2eassemblyinfo_2ecs_15',['StarterApp.Migrations.AssemblyInfo.cs',['../_starter_app_8_migrations_8_assembly_info_8cs.html',1,'']]],
  ['starterapp_2emigrations_2eglobalusings_2eg_2ecs_16',['StarterApp.Migrations.GlobalUsings.g.cs',['../net8_80_2_starter_app_8_migrations_8_global_usings_8g_8cs.html',1,'(Global Namespace)'],['../net9_80_2_starter_app_8_migrations_8_global_usings_8g_8cs.html',1,'(Global Namespace)']]],
  ['starterapp_2enfloat_2eg_2ecs_17',['StarterApp.nfloat.g.cs',['../net8_80-maccatalyst_2maccatalyst-x64_2_starter_app_8nfloat_8g_8cs.html',1,'(Global Namespace)'],['../net9_80-maccatalyst_2maccatalyst-x64_2_starter_app_8nfloat_8g_8cs.html',1,'(Global Namespace)']]],
  ['starterapp_3a_3aconverters_18',['Converters',['../namespace_starter_app_1_1_converters.html',1,'StarterApp']]],
  ['starterapp_3a_3adatabase_19',['Database',['../namespace_starter_app_1_1_database.html',1,'StarterApp']]],
  ['starterapp_3a_3adatabase_3a_3adata_20',['Data',['../namespace_starter_app_1_1_database_1_1_data.html',1,'StarterApp::Database']]],
  ['starterapp_3a_3adatabase_3a_3amigrations_21',['Migrations',['../namespace_starter_app_1_1_database_1_1_migrations.html',1,'StarterApp::Database']]],
  ['starterapp_3a_3adatabase_3a_3amodels_22',['Models',['../namespace_starter_app_1_1_database_1_1_models.html',1,'StarterApp::Database']]],
  ['starterapp_3a_3aservices_23',['Services',['../namespace_starter_app_1_1_services.html',1,'StarterApp']]],
  ['starterapp_3a_3astarterapp_5fxamltypeinfo_24',['StarterApp_XamlTypeInfo',['../namespace_starter_app_1_1_starter_app___xaml_type_info.html',1,'StarterApp']]],
  ['starterapp_3a_3aviewmodels_25',['ViewModels',['../namespace_starter_app_1_1_view_models.html',1,'StarterApp']]],
  ['starterapp_3a_3aviews_26',['Views',['../namespace_starter_app_1_1_views.html',1,'StarterApp']]],
  ['starterapp_3a_3awinui_27',['WinUI',['../namespace_starter_app_1_1_win_u_i.html',1,'StarterApp']]],
  ['stringtoboolconverter_28',['StringToBoolConverter',['../class_starter_app_1_1_converters_1_1_string_to_bool_converter.html',1,'StarterApp::Converters']]],
  ['stringtoboolconverter_2ecs_29',['StringToBoolConverter.cs',['../_string_to_bool_converter_8cs.html',1,'']]],
  ['success_30',['Success',['../class_starter_app_1_1_services_1_1_auth_result.html#a8bc4c7f8048ef53f3fd9405708fe3e7e',1,'StarterApp::Services::AuthResult']]],
  ['successmessage_31',['SuccessMessage',['../class_starter_app_1_1_view_models_1_1_user_detail_view_model.html#a6b53c62e647a40eb7ef40b7619156558',1,'StarterApp::ViewModels::UserDetailViewModel']]]
];
